spring:

  application:
    name: moneyway-service
  kafka:
    consumer:
      bootstrap-servers: my-cluster-kafka-bootstrap:9092
      group-id: "betio-moneyway"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: my-cluster-kafka-bootstrap:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    mongodb:
      host: '${MONGO_HOST}'
      database: '${MONGO_DB}'
      port: 27017
      username: '${MONGO_USERNAME}'
      password: '${MONGO_PASSWORD}'
  cloud:
    kubernetes:
      discovery:
        register: true
      secrets:
        name: mongo-secret
      config:
        enabled: true
        sources:
          - namespace: default
            name: mongo-conf
      reload:
        enabled: true
        mode: polling
        period: 1000
management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
